/* ═══════════════════════════════════════════════════════════════
   VITRUVIAN — CONTENT LAYER
   ───────────────────────────────────────────────────────────────
   Branding (CONFIG), the thinking-model library (MODEL_LIBRARY),
   and UI copy (COPY). The engine never contains copy; this file
   never contains rendering, storage, or generation logic.

   FORK CHECKLIST — same discipline as UX-First Studio:
   1. Copy the whole folder.
   2. Edit CONFIG (name, tagline, accent trio, storageKey — or
      saved data collides between forks on the same origin).
   3. Edit manifest.webmanifest (name, colors) + regenerate icons.
   4. Bump CACHE_VERSION in sw.js on EVERY deploy.
   ═══════════════════════════════════════════════════════════════ */

/* ---------- CONFIG ---------- */
var CONFIG = {
  toolName: "Vitruvian",
  tagline:  "The anatomy of everyday systems, simplified",
  accent:     "#0e7a63",
  accentDeep: "#0a5748",
  accentWash: "#e2f0ec",
  failure:    "#c22f2f",
  money:      "#9a6212",
  vermillion: "#D95B31",                // EnsoKit seal — human completion marks only
  storageKey: "system_deconstructor_v1",  // NEVER change: existing installs' data lives under this key
  appVersion: "1.10.0",
  flagshipVersion: 2                     // bump when flagship JSON content changes → re-seeds for existing users (attempts preserved)
};

/* ---------- ENSO_ICONS — brush marks for the landing cards ----------
   Path-d arrays generated by tools/make-enso.js from EnsoKit's brush engine.
   Rendered as inline currentColor SVG (themeable) by the engine. Regenerate
   with `node tools/make-enso.js` and paste its ENSO_ICONS output here. */
var ENSO_ICONS = {"whatItIs":["M65 20L69 21L73 23L76 25L79 28L82 31L84 35L86 39L87 43L88 47L88 52L88 56L87 60L86 65L84 69L82 73L80 77L76 80L73 83L69 85L65 87L60 88L56 88L52 88L47 88L43 87L39 86L35 84L31 82L28 79L25 77L22 74L19 70L17 66L16 63L15 59L14 54L15 50L15 46L16 42L18 39L20 35L22 32L24 29L27 26L29 29L27 31L25 34L23 37L21 40L20 43L19 47L19 50L19 54L19 58L20 61L21 64L23 68L26 70L28 73L31 75L34 77L37 79L41 80L44 81L48 82L51 82L55 82L59 81L62 80L66 79L69 77L72 74L74 71L76 68L77 65L78 62L79 58L79 55L79 51L79 48L78 45L77 42L76 39L75 36L74 32L72 29L70 26L67 24L65 21Z"],"whoFor":["M56 16L60 16L65 17L69 18L74 20L78 23L81 26L84 30L86 35L87 39L88 44L88 49L88 54L87 58L86 63L84 67L82 71L79 75L75 78L72 81L67 84L63 85L58 86L54 87L49 86L45 85L41 84L37 82L33 80L30 77L27 74L24 71L22 68L20 64L18 60L17 56L16 52L16 48L16 43L17 39L18 35L21 31L23 28L26 25L29 22L31 24L28 26L25 29L23 33L21 36L20 40L19 44L19 48L19 52L20 56L21 59L23 63L25 66L27 69L29 71L32 74L35 76L38 78L42 80L45 81L49 82L53 82L57 82L61 81L65 79L69 77L72 75L75 72L77 68L79 65L80 61L81 57L82 53L82 49L82 45L81 41L80 37L78 34L76 30L73 27L71 24L67 22L64 20L60 18L56 17Z","M44.0 44.0L43.7 45.4L42.9 46.5L41.8 47.3L40.9 48.2L39.8 49.5L38.1 50.0L36.7 49.0L36.0 47.4L35.4 46.3L34.5 45.3L34.0 44.0L34.1 42.6L34.5 41.1L35.3 39.7L36.8 39.1L38.4 39.6L39.6 40.1L40.9 39.9L42.6 39.9L43.8 40.9L44.1 42.5Z","M64.85 44.00L64.68 45.08L65.35 46.80L65.23 48.88L63.58 49.65L61.70 48.86L60.41 48.09L59.21 47.92L57.99 47.47L57.04 46.54L55.96 45.48L54.85 44.00L55.08 42.26L56.94 41.39L58.68 41.33L59.43 40.55L60.28 38.96L61.83 38.19L63.36 38.82L64.54 39.91L65.46 41.14L65.55 42.66Z","M55.552 63.000L55.147 64.511L54.255 65.734L53.007 66.470L52.008 67.396L50.857 68.961L49.017 69.839L47.361 68.778L46.716 66.790L46.275 65.394L45.306 64.378L44.552 63.000L44.593 61.412L45.001 59.787L45.803 58.157L47.438 57.390L49.292 58.073L50.582 58.951L51.931 58.772L53.919 58.477L55.528 59.447L55.860 61.279Z"],"whyWorks":["M63 17L67 18L72 20L76 23L79 26L83 30L85 34L87 39L87 43L87 48L87 53L85 57L84 62L81 66L79 69L76 73L73 76L69 79L66 81L62 83L57 85L53 85L48 86L44 86L39 85L35 83L31 81L27 78L24 75L21 71L18 67L16 63L15 59L14 54L13 50L14 45L14 40L15 36L17 31L20 27L23 23L27 20L31 17L35 16L40 14L40 17L36 18L32 20L28 22L25 25L22 29L20 33L18 37L17 41L17 45L17 50L18 54L19 58L20 62L22 65L24 69L27 72L30 75L33 77L37 79L41 80L45 80L49 81L52 80L56 79L60 78L63 76L66 74L69 71L71 69L74 66L76 63L77 60L79 56L79 52L80 49L80 45L79 41L78 37L77 33L75 30L72 26L70 23L66 20L62 18Z","M59.6 50.0L58.2 52.4L56.1 53.9L54.5 55.2L52.8 56.1L50.9 56.2L49.0 56.7L46.4 57.8L43.5 57.4L42.6 54.7L43.9 51.8L44.6 50.0L43.8 48.2L43.4 45.8L44.7 43.8L46.5 42.4L48.8 41.4L51.2 41.8L52.7 44.1L53.4 46.1L55.2 46.6L58.3 47.6Z"],"howTo":["M59 16L64 17L68 19L72 21L76 23L79 26L82 29L85 33L87 38L88 42L89 47L89 52L88 56L86 61L84 65L82 69L79 72L76 75L72 78L68 80L64 82L60 83L56 84L52 85L48 85L43 85L39 84L35 82L31 80L28 78L25 75L22 71L20 68L18 64L17 60L16 56L15 51L16 47L16 43L17 39L18 35L20 31L22 27L25 24L28 20L30 22L27 25L24 29L22 32L21 36L20 40L19 43L18 47L18 51L19 55L20 59L21 62L23 66L25 69L27 72L30 75L33 77L37 79L40 80L44 80L48 81L52 80L55 80L59 79L62 77L66 76L69 74L72 72L75 69L77 66L79 63L81 59L82 55L82 51L82 48L82 44L80 40L79 36L77 33L74 30L72 27L69 24L66 22L63 19L59 17Z","M33.6 63.8L35.0 63.3L36.7 62.4L38.7 61.3L40.8 59.9L43.0 58.4L45.2 56.8L47.5 55.2L49.6 53.6L51.7 52.2L53.7 50.7L55.8 49.1L58.0 47.4L60.2 45.7L62.1 43.9L63.9 42.1L65.4 40.4L66.6 38.8L67.4 37.5L66.6 36.5L65.1 36.9L63.3 37.7L61.3 38.7L59.1 39.9L56.8 41.3L54.6 42.9L52.4 44.6L50.3 46.3L48.3 47.8L46.4 49.4L44.3 51.1L42.2 52.8L40.0 54.6L38.0 56.3L36.1 57.9L34.5 59.5L33.3 61.0L32.4 62.2Z"]};

/* ---------- MODEL_LIBRARY · the 14 thinking models ----------
   Every layer's problem names exactly one of these. Their ids are
   the contract between generated documents, the validator, and
   the cross-system Models index. Do not rename ids casually —
   saved breakdowns reference them forever. */
var MODEL_LIBRARY = [
  {
    id: "first-principles",
    name: "First Principles",
    one_liner: "Strip every assumption; rebuild from what must be true.",
    description: "Take the problem apart until you reach facts that cannot be argued with, then build the solution up from only those. Most designs inherit assumptions from their predecessors; first-principles thinking asks which inherited beliefs are actually load-bearing — and deletes the rest. The railway's block system was born this way: safety requires knowing a track is empty, not assuming it after enough time has passed."
  },
  {
    id: "inversion",
    name: "Inversion",
    one_liner: "Design by asking how it would fail, then make that impossible.",
    description: "Instead of asking 'how do I make this work?', enumerate the ways it could go wrong and design each one out. Interlocking frames, checklists, and type systems are all inversion at work: list the conflicting moves, then make them mechanically unexpressible rather than merely forbidden."
  },
  {
    id: "bottleneck",
    name: "Bottleneck Analysis",
    one_liner: "Find the one constraint that governs the whole system's throughput.",
    description: "Every system has a narrowest point, and the system as a whole cannot go faster than it. Optimizing anywhere else is invisible. Find the bottleneck, widen it or route around it, then find the new one — because there is always a new one."
  },
  {
    id: "feedback-loop",
    name: "Feedback Loops",
    one_liner: "Feed the output back as input; the loop stabilizes or amplifies.",
    description: "A system that senses its own state can correct it (negative feedback: thermostats, track circuits) or runaway-amplify it (positive feedback: viral sharing, bank runs). Ask what the system measures about itself, how fast that signal travels, and whether the loop damps errors or compounds them."
  },
  {
    id: "single-source-of-truth",
    name: "Single Source of Truth",
    one_liner: "One authoritative record; everything else is a copy that can be wrong.",
    description: "When two records can disagree, one of them is lying and the system must decide which. Designating a single authoritative source turns conflict resolution into a lookup. Timetables, land registries, and primary databases all answer the same question: when copies diverge, who wins?"
  },
  {
    id: "mutual-exclusion",
    name: "Mutual Exclusion",
    one_liner: "One-at-a-time access enforced by possession, not politeness.",
    description: "When a shared resource can only safely serve one user at a time, etiquette is not enforcement. Make permission a thing that can be held — a token, a lock, a lease — so that uniqueness is physical, not behavioral. Two people cannot hold one brass key."
  },
  {
    id: "queue-and-buffer",
    name: "Queues & Buffers",
    one_liner: "Decouple producers from consumers; absorb bursts with waiting room.",
    description: "When arrivals are bursty and service is steady, something must give: either arrivals are rejected or they wait. A buffer converts a rate mismatch into latency instead of loss. The follow-up questions are always the same: how long can the queue grow, what happens when it's full, and who waits?"
  },
  {
    id: "redundancy",
    name: "Redundancy & Failover",
    one_liner: "No single point of failure; spares that take over when parts die.",
    description: "Any component will eventually fail; the design question is whether the system fails with it. Redundancy buys survival with duplication — spare parts, second paths, replicas — and introduces its own hard problem: detecting failure and switching over without making things worse."
  },
  {
    id: "separation-of-concerns",
    name: "Separation of Concerns",
    one_liner: "Split responsibilities so parts can change without breaking each other.",
    description: "Bundle unrelated responsibilities together and every change risks everything at once. Separate them behind clear boundaries and each part can evolve, fail, and scale on its own. The boundary is the design: what one side promises the other is the system's real architecture."
  },
  {
    id: "trust-boundary",
    name: "Trust Boundaries",
    one_liner: "Decide where verification happens; never trust across the line.",
    description: "Every system has lines where data or people cross from 'unverified' to 'trusted'. Security failures are almost always a crossing that skipped its checkpoint. Draw the boundaries explicitly, verify at each crossing, and assume everything outside is hostile — not because it is, but because you can't tell."
  },
  {
    id: "incentive-alignment",
    name: "Incentive Alignment",
    one_liner: "Make the selfish choice and the correct choice the same choice.",
    description: "Systems run by people do what the incentives reward, not what the rules say. If the profitable action and the intended action diverge, the system drifts toward profit. Durable designs make honest behavior the cheapest path — aligning what actors want with what the system needs."
  },
  {
    id: "graceful-degradation",
    name: "Graceful Degradation",
    one_liner: "Partial failure yields reduced service, not collapse.",
    description: "The question is never whether parts fail but what the whole does when they do. Fail-safe defaults (a dead signal shows red; released brakes engage) choose the harmless state when knowledge is lost. Degrading gracefully means the system keeps serving — slower, dumber, safer — instead of stopping."
  },
  {
    id: "locality-and-caching",
    name: "Locality & Caching",
    one_liner: "Put copies near demand; pay for speed with staleness.",
    description: "Distance is latency, and most demand is concentrated and repetitive. Keeping copies close to where they're wanted converts far, slow, expensive reads into near, fast, cheap ones. The bill arrives as staleness: every cache is a bet that the original hasn't changed since you copied it."
  },
  {
    id: "idempotency",
    name: "Idempotency",
    one_liner: "Safe retries: doing it twice equals doing it once.",
    description: "Unreliable channels force a brutal choice — retry and risk duplicates, or don't and risk loss. Idempotent operations dissolve the dilemma: design the action so repeating it changes nothing, and retries become free. Message ids, payment ids, and 'set' instead of 'increment' are all the same move."
  }
];

/* ---------- UI COPY ---------- */
var COPY = {
  libraryTitle: "Library",
  sampleHeading: "Sample Deconstructs",
  sampleNote: "Three worked examples — the bar for what a study looks like.",
  yoursHeading: "Your Deconstructions",
  yoursEmpty: "Nothing here yet. Name any system above and Vitruvian will take it apart, failure by failure.",
  deconstructPlaceholder: "Name a system to study…",
  deconstructBtn: "Deconstruct",
  ownDesignLink: "Building something? Deconstruct your own design →",
  ownDesignKicker: "Design review",
  ownDesignTitle: "Deconstruct your design",
  ownDesignLede: "Describe the system you're building — the pieces, what it must never get wrong, where you expect load. Vitruvian rebuilds it failure by failure and shows what breaks first.",
  ownDesignPlaceholder: "e.g. A booking app where vendors set their availability and customers reserve time slots. Two customers must never book the same slot; vendors get notified the instant a booking lands; I expect big spikes when a popular vendor opens their calendar…",
  ownDesignBtn: "Review my design",
  audienceModes: [
    { id: "beginner",   label: "Beginner" },
    { id: "enthusiast", label: "Enthusiast" },
    { id: "developer",  label: "Developer" }
  ],
  gateKicker: "Before the reveal — your turn",
  gateHint1: "Show the thinking model",
  gateHint2: "One more hint",
  gateReveal: "Reveal the solution",
  gateCompare: "Compare my answer (AI)",
  askTitle: "Ask this layer",
  askPlaceholder: "One question — e.g. \"why not just use timestamps?\"",
  askBtn: "Ask",
  whatifMenu: "What if… (propose a change)",
  whatifKicker: "What if",
  whatifLede: "Propose a change to this system. Vitruvian shows what it does to the architecture, which invariants it strengthens or threatens, and whether it's worth it — grounded in the system's own rules.",
  whatifPlaceholder: "e.g. add an HTML renderer to the terminal · cache reads at the edge · drop the acknowledgement step",
  whatifBtn: "Run what-if",
  whatifThinking: "Weighing it against the invariants…",
  whatifVerdicts: { improves: "Improves the system", mixed: "A real tradeoff", harmful: "Works against the system" },
  gateCompareOffline: "AI comparison needs a connection and an API key (Settings). Your answer is saved — compare it yourself against the reveal.",
  keyNotice: "Your key is stored on this device only and sent only to Anthropic.",
  costNote: "A breakdown typically costs a few cents to a few tens of cents of API usage, depending on the model.",
  modelCostNote: "Rough cost per study — haiku-4-5 ≈ $0.10 · sonnet-5 ≈ $0.30 · opus-4-8 ≈ $0.55 · fable-5 ≈ $1.20. Fable is the most capable and auto-falls back to Opus if it declines a request.",
  pricingUrl: "https://www.anthropic.com/pricing",
  privacyNote: "Everything lives on this device. Breakdowns, attempts, and your key are never sent anywhere except your own calls to Anthropic.",
  offlineGenNote: "Generation needs a connection. Reading never does.",
  bridgeToast: "Reference notes copied — paste into UX-First Studio's Structure It station.",
  studioUrl: "https://bate-epey93.github.io/uxfirst-studio/",
  /* ---------- LANDING (first-run explainer) ---------- */
  landing: {
    kicker: "Welcome to Vitruvian",
    headline: "Take anything apart.\nPut it back together. Now you get it.",
    lede: "Everyday systems — the railway, WhatsApp, YouTube — rebuilt from scratch, one failure at a time.",
    sections: [
      { icon: "whatItIs", title: "What it is",
        body: "Pick a system. Vitruvian strips it to its bones, then rebuilds it layer by layer — each layer born from a real failure (yes, real train crashes). A diagram grows as it comes together." },
      { icon: "whoFor", title: "Who it's for",
        body: "Curious minds, systems-design enthusiasts, and developers prepping for architecture interviews. Three reading levels, from plain English to engineer." },
      { icon: "whyWorks", title: "Why it works",
        body: "You remember what you rebuild. Design each fix yourself before the reveal — and collect the named thinking models that repeat across systems." },
      { icon: "howTo", title: "How to use it",
        body: "Start with a sample study. Add your Anthropic API key in Settings to deconstruct anything you name. Works offline; installs to your home screen." }
    ],
    cta: "Start exploring →",
    footnote: "No account. No cloud. Your studies stay on this device."
  },

  /* ---------- TUTORIAL — 'How to read a study' (visitable anytime) ---------- */
  tutorial: {
    kicker: "How to read a study",
    headline: "Every study is the same shape.",
    lede: "A Vitruvian study rebuilds a system from nothing, one failure at a time. Here's how to read the pieces — and, for developers, how to lift a technical spec straight out of one.",
    reading: {
      title: "The path through a study",
      steps: [
        ["Essence", "The system in one breath, plus a few surprising, checkable facts."],
        ["Strip-down", "The irreducible core: who wants what, the invariants (what must never be false), the pieces, the flows, and the hard constraints physics and economics impose."],
        ["The rebuild", "4–7 layers, and the heart of it. Each layer is forced by a concrete failure of the version before it — often a real, dated disaster — so you watch the design become necessary, not just described."],
        ["Stress tests", "Push the finished system somewhere nasty and see how it copes, or where it honestly breaks."],
        ["Transfer", "The system-neutral principles, and where the same shapes recur in other systems."]
      ]
    },
    cards: {
      title: "Inside each layer — the cards",
      note: "One layer, read top to bottom. Several cards are interactive — tap to locate them on the diagram.",
      items: [
        ["problem", "The problem", "The failure that forces this layer to exist. Tap it to flash — in red — exactly what breaks on the diagram."],
        ["model", "Thinking model", "The named, reusable pattern that cracks the problem (there are 14). Tap any model in the Models index to see it recur across systems."],
        ["solution", "What was actually built", "The mechanism itself. Tap it to light — in teal — what this layer adds to the diagram."],
        ["lens", "For the people · Under the hood", "Two lenses side by side: what users gain and what they pay, versus how it works and the transferable principle."],
        ["tradeoff", "The tradeoff", "What this layer sacrifices. Nothing is free — safety costs capacity, caching costs freshness."],
        ["scale", "Under load", "How the mechanism holds as load grows — its scaling property, its ceiling, or the sharding/caching it forces. Tap it to trace the load path in gold."],
        ["defends", "Defends", "Which invariants from the strip-down this layer protects, by number."],
        ["dev", "For engineers", "Mechanism → software-concept mappings, plus interview probes. In Developer mode this reads as spec-grade material."],
        ["analogy", "In everyday terms", "One plain analogy, for when an idea needs grounding."]
      ]
    },
    diagram: {
      title: "Reading the diagram",
      intro: "The diagram grows as the system does — every layer adds to it, and it never re-arranges. Colour means role, shape means kind, and the arrows show what moves.",
      nodeKinds: [
        ["actor", "Actor", "a person or party"],
        ["store", "Store", "where things wait or accumulate"],
        ["process", "Process", "where work happens"],
        ["channel", "Channel", "what things move through"]
      ],
      edgeKinds: [
        ["payload", "Payload", "the thing the system exists to move (solid line). This is the load path."],
        ["control", "Control", "signals and permissions (dashed) — often flowing back, against the payload."],
        ["money", "Money", "value changing hands (gold, dotted)."]
      ],
      extra: [
        ["Lanes & colour", "Horizontal bands are semantic roles — People, Service, Control, Money — each with its own colour. An arrow wears the colour of the lane its input comes from, so you can see at a glance who is driving what."],
        ["The red pulse", "At a gate, or when you tap the problem card, the parts about to break pulse red — you see the failure before you see the fix."],
        ["Spotlight", "Tap a card to light its parts and dim the rest: the problem card lights what breaks (red), the solution card lights what's added (teal), and Under load traces the path load travels (gold)."],
        ["Pan & scrub", "Dense diagrams pan sideways. Drag the scrubber (0…N) under the diagram to sweep it from the naive baseline to the finished system."]
      ]
    },
    controls: {
      title: "Controls",
      items: [
        ["Audience — B / E / D", "Three registers of the same study: Beginner (plain language, everyday analogies), Enthusiast (the default), and Developer (adds the engineer mappings and interview probes). Switch anytime; your place is kept."],
        ["Step & scrub", "Move layer by layer with Prev / Next, or drag the scrubber to sweep the diagram across every state."],
        ["Challenge mode", "Optional, and off by default. Turn it on from the ⋯ menu to hide each solution behind a 'design it first' gate — you predict the fix, then compare."]
      ]
    },
    forDev: {
      title: "For developers — reading a study as a spec",
      intro: "A study is already shaped like a design document. Switch to Developer mode first (it surfaces the mappings and probes the other registers tuck away), then lift it across:",
      map: [
        ["Strip-down", "system context — actors, invariants (your correctness guarantees), entities, data flows, and hard constraints."],
        ["Each layer's mechanism + principle", "an architecture decision record: what you built and the rule it encodes."],
        ["Under load", "the scaling / capacity section: throughput ceilings, bottlenecks, and the sharding or caching strategy."],
        ["Tradeoffs + stress tests", "your risk register and failure-mode analysis."],
        ["For-engineers mappings", "the concrete tech — the software concept each mechanism maps to."],
        ["Transfer principles", "the reusable patterns to carry into your own design."]
      ]
    },
    cta: "Got it — back to reading"
  },

  genPhases: {
    start:      "Reading the system…",
    strip_down: "Stripping it down…",
    visual:     "Drawing the baseline…",
    layers:     "Rebuilding — layer by layer…",
    stress:     "Stress-testing…",
    transfer:   "Extracting principles…"
  }
};
