/* ═══════════════════════════════════════════════════════════════
   VITRUVIAN — CONTENT LAYER
   ───────────────────────────────────────────────────────────────
   Branding (CONFIG), the thinking-model library (MODEL_LIBRARY),
   and UI copy (COPY). The engine never contains copy; this file
   never contains rendering, storage, or generation logic.

   FORK CHECKLIST — same discipline as UX-First Studio:
   1. Copy the whole folder.
   2. Edit CONFIG (name, tagline, accent trio, storageKey — or
      saved data collides between forks on the same origin).
   3. Edit manifest.webmanifest (name, colors) + regenerate icons.
   4. Bump CACHE_VERSION in sw.js on EVERY deploy.
   ═══════════════════════════════════════════════════════════════ */

/* ---------- CONFIG ---------- */
var CONFIG = {
  toolName: "Vitruvian",
  tagline:  "The anatomy of everyday systems, simplified",
  accent:     "#0e7a63",
  accentDeep: "#0a5748",
  accentWash: "#e2f0ec",
  failure:    "#c22f2f",
  money:      "#9a6212",
  vermillion: "#D95B31",                // EnsoKit seal — human completion marks only
  storageKey: "system_deconstructor_v1",  // NEVER change: existing installs' data lives under this key
  appVersion: "1.24.0",
  flagshipVersion: 9,                    // bump when flagship JSON content changes → re-seeds for existing users (attempts preserved)
  // foundations first, then the systems built on them — YouTube last, the capstone that drills into everything
  flagshipNames: ["unique-id-generator", "distributed-cache", "object-storage", "message-queue", "notification-system", "url-shortener", "content-delivery-network", "recommendation-feed", "video-transcoding", "news-feed", "whatsapp", "youtube", "railway"],
  siteUrl: "https://bate-epey93.github.io/vitruvian/",
  repoUrl: "https://github.com/Bate-Epey93/vitruvian"
};

/* ---------- ENSO_ICONS — brush marks for the landing cards ----------
   Path-d arrays generated by tools/make-enso.js from EnsoKit's brush engine.
   Rendered as inline currentColor SVG (themeable) by the engine. Regenerate
   with `node tools/make-enso.js` and paste its ENSO_ICONS output here. */
var ENSO_ICONS = {"whatItIs":["M65 20L69 21L73 23L76 25L79 28L82 31L84 35L86 39L87 43L88 47L88 52L88 56L87 60L86 65L84 69L82 73L80 77L76 80L73 83L69 85L65 87L60 88L56 88L52 88L47 88L43 87L39 86L35 84L31 82L28 79L25 77L22 74L19 70L17 66L16 63L15 59L14 54L15 50L15 46L16 42L18 39L20 35L22 32L24 29L27 26L29 29L27 31L25 34L23 37L21 40L20 43L19 47L19 50L19 54L19 58L20 61L21 64L23 68L26 70L28 73L31 75L34 77L37 79L41 80L44 81L48 82L51 82L55 82L59 81L62 80L66 79L69 77L72 74L74 71L76 68L77 65L78 62L79 58L79 55L79 51L79 48L78 45L77 42L76 39L75 36L74 32L72 29L70 26L67 24L65 21Z"],"whoFor":["M56 16L60 16L65 17L69 18L74 20L78 23L81 26L84 30L86 35L87 39L88 44L88 49L88 54L87 58L86 63L84 67L82 71L79 75L75 78L72 81L67 84L63 85L58 86L54 87L49 86L45 85L41 84L37 82L33 80L30 77L27 74L24 71L22 68L20 64L18 60L17 56L16 52L16 48L16 43L17 39L18 35L21 31L23 28L26 25L29 22L31 24L28 26L25 29L23 33L21 36L20 40L19 44L19 48L19 52L20 56L21 59L23 63L25 66L27 69L29 71L32 74L35 76L38 78L42 80L45 81L49 82L53 82L57 82L61 81L65 79L69 77L72 75L75 72L77 68L79 65L80 61L81 57L82 53L82 49L82 45L81 41L80 37L78 34L76 30L73 27L71 24L67 22L64 20L60 18L56 17Z","M44.0 44.0L43.7 45.4L42.9 46.5L41.8 47.3L40.9 48.2L39.8 49.5L38.1 50.0L36.7 49.0L36.0 47.4L35.4 46.3L34.5 45.3L34.0 44.0L34.1 42.6L34.5 41.1L35.3 39.7L36.8 39.1L38.4 39.6L39.6 40.1L40.9 39.9L42.6 39.9L43.8 40.9L44.1 42.5Z","M64.85 44.00L64.68 45.08L65.35 46.80L65.23 48.88L63.58 49.65L61.70 48.86L60.41 48.09L59.21 47.92L57.99 47.47L57.04 46.54L55.96 45.48L54.85 44.00L55.08 42.26L56.94 41.39L58.68 41.33L59.43 40.55L60.28 38.96L61.83 38.19L63.36 38.82L64.54 39.91L65.46 41.14L65.55 42.66Z","M55.552 63.000L55.147 64.511L54.255 65.734L53.007 66.470L52.008 67.396L50.857 68.961L49.017 69.839L47.361 68.778L46.716 66.790L46.275 65.394L45.306 64.378L44.552 63.000L44.593 61.412L45.001 59.787L45.803 58.157L47.438 57.390L49.292 58.073L50.582 58.951L51.931 58.772L53.919 58.477L55.528 59.447L55.860 61.279Z"],"whyWorks":["M63 17L67 18L72 20L76 23L79 26L83 30L85 34L87 39L87 43L87 48L87 53L85 57L84 62L81 66L79 69L76 73L73 76L69 79L66 81L62 83L57 85L53 85L48 86L44 86L39 85L35 83L31 81L27 78L24 75L21 71L18 67L16 63L15 59L14 54L13 50L14 45L14 40L15 36L17 31L20 27L23 23L27 20L31 17L35 16L40 14L40 17L36 18L32 20L28 22L25 25L22 29L20 33L18 37L17 41L17 45L17 50L18 54L19 58L20 62L22 65L24 69L27 72L30 75L33 77L37 79L41 80L45 80L49 81L52 80L56 79L60 78L63 76L66 74L69 71L71 69L74 66L76 63L77 60L79 56L79 52L80 49L80 45L79 41L78 37L77 33L75 30L72 26L70 23L66 20L62 18Z","M59.6 50.0L58.2 52.4L56.1 53.9L54.5 55.2L52.8 56.1L50.9 56.2L49.0 56.7L46.4 57.8L43.5 57.4L42.6 54.7L43.9 51.8L44.6 50.0L43.8 48.2L43.4 45.8L44.7 43.8L46.5 42.4L48.8 41.4L51.2 41.8L52.7 44.1L53.4 46.1L55.2 46.6L58.3 47.6Z"],"howTo":["M59 16L64 17L68 19L72 21L76 23L79 26L82 29L85 33L87 38L88 42L89 47L89 52L88 56L86 61L84 65L82 69L79 72L76 75L72 78L68 80L64 82L60 83L56 84L52 85L48 85L43 85L39 84L35 82L31 80L28 78L25 75L22 71L20 68L18 64L17 60L16 56L15 51L16 47L16 43L17 39L18 35L20 31L22 27L25 24L28 20L30 22L27 25L24 29L22 32L21 36L20 40L19 43L18 47L18 51L19 55L20 59L21 62L23 66L25 69L27 72L30 75L33 77L37 79L40 80L44 80L48 81L52 80L55 80L59 79L62 77L66 76L69 74L72 72L75 69L77 66L79 63L81 59L82 55L82 51L82 48L82 44L80 40L79 36L77 33L74 30L72 27L69 24L66 22L63 19L59 17Z","M33.6 63.8L35.0 63.3L36.7 62.4L38.7 61.3L40.8 59.9L43.0 58.4L45.2 56.8L47.5 55.2L49.6 53.6L51.7 52.2L53.7 50.7L55.8 49.1L58.0 47.4L60.2 45.7L62.1 43.9L63.9 42.1L65.4 40.4L66.6 38.8L67.4 37.5L66.6 36.5L65.1 36.9L63.3 37.7L61.3 38.7L59.1 39.9L56.8 41.3L54.6 42.9L52.4 44.6L50.3 46.3L48.3 47.8L46.4 49.4L44.3 51.1L42.2 52.8L40.0 54.6L38.0 56.3L36.1 57.9L34.5 59.5L33.3 61.0L32.4 62.2Z"]};

/* ---------- MODEL_LIBRARY · the 14 thinking models ----------
   Every layer's problem names exactly one of these. Their ids are
   the contract between generated documents, the validator, and
   the cross-system Models index. Do not rename ids casually —
   saved breakdowns reference them forever. */
var MODEL_LIBRARY = [
  {
    id: "first-principles",
    name: "First Principles",
    one_liner: "Strip every assumption; rebuild from what must be true.",
    description: "Take the problem apart until you reach facts that cannot be argued with, then build up from only those. Most designs inherit assumptions from their predecessors; first-principles thinking asks which inherited beliefs are load-bearing and deletes the rest. The railway's block system was born this way: safety requires knowing a track is empty, not assuming it after enough time has passed."
  },
  {
    id: "inversion",
    name: "Inversion",
    one_liner: "Design by asking how it would fail, then make that impossible.",
    description: "Instead of asking 'how do I make this work?', list the ways it could go wrong and design each one out. Interlocking frames, checklists, and type systems are all inversion at work: name the conflicting moves, then make them impossible to express rather than merely forbidden."
  },
  {
    id: "bottleneck",
    name: "Bottleneck Analysis",
    one_liner: "Find the one constraint that governs the whole system's throughput.",
    description: "Every system has a narrowest point, and the system as a whole cannot go faster than it. Optimizing anywhere else is invisible. Find the bottleneck, widen it or route around it, then find the new one; there is always a new one."
  },
  {
    id: "feedback-loop",
    name: "Feedback Loops",
    one_liner: "Feed the output back as input; the loop stabilizes or amplifies.",
    description: "A system that senses its own state can correct it (negative feedback: thermostats, track circuits) or runaway-amplify it (positive feedback: viral sharing, bank runs). Ask what the system measures about itself, how fast that signal travels, and whether the loop damps errors or compounds them."
  },
  {
    id: "single-source-of-truth",
    name: "Single Source of Truth",
    one_liner: "One authoritative record; everything else is a copy that can be wrong.",
    description: "When two records can disagree, one of them is lying and the system must decide which. Designating a single authoritative source turns conflict resolution into a lookup. Timetables, land registries, and primary databases all answer the same question: when copies diverge, who wins?"
  },
  {
    id: "mutual-exclusion",
    name: "Mutual Exclusion",
    one_liner: "One-at-a-time access enforced by possession, not politeness.",
    description: "When a shared resource can only safely serve one user at a time, etiquette is not enforcement. Make permission a thing that can be held: a token, a lock, a lease. Then uniqueness is physical, not behavioral. Two people cannot hold one brass key."
  },
  {
    id: "queue-and-buffer",
    name: "Queues & Buffers",
    one_liner: "Decouple producers from consumers; absorb bursts with waiting room.",
    description: "When arrivals are bursty and service is steady, something must give: either arrivals are rejected or they wait. A buffer converts a rate mismatch into latency instead of loss. The follow-up questions are always the same: how long can the queue grow, what happens when it's full, and who waits?"
  },
  {
    id: "redundancy",
    name: "Redundancy & Failover",
    one_liner: "No single point of failure; spares that take over when parts die.",
    description: "Any component will eventually fail; the design question is whether the system fails with it. Redundancy buys survival with duplication: spare parts, second paths, replicas. It also brings its own hard problem, detecting failure and switching over without making things worse."
  },
  {
    id: "separation-of-concerns",
    name: "Separation of Concerns",
    one_liner: "Split responsibilities so parts can change without breaking each other.",
    description: "Bundle unrelated responsibilities together and every change risks everything at once. Separate them behind clear boundaries and each part can evolve, fail, and scale on its own. The boundary is the design: what one side promises the other is the system's real architecture."
  },
  {
    id: "trust-boundary",
    name: "Trust Boundaries",
    one_liner: "Decide where verification happens; never trust across the line.",
    description: "Every system has lines where data or people cross from 'unverified' to 'trusted'. Security failures are almost always a crossing that skipped its checkpoint. Draw the boundaries explicitly, verify at each crossing, and assume everything outside is hostile: not because it is, but because you can't tell."
  },
  {
    id: "incentive-alignment",
    name: "Incentive Alignment",
    one_liner: "Make the selfish choice and the correct choice the same choice.",
    description: "Systems run by people do what the incentives reward, not what the rules say. If the profitable action and the intended action diverge, the system drifts toward profit. Durable designs make honest behavior the cheapest path, so what actors want lines up with what the system needs."
  },
  {
    id: "graceful-degradation",
    name: "Graceful Degradation",
    one_liner: "Partial failure yields reduced service, not collapse.",
    description: "The question is never whether parts fail but what the whole does when they do. Fail-safe defaults (a dead signal shows red; released brakes engage) choose the harmless state when knowledge is lost. Degrading gracefully means the system keeps serving, slower and dumber but safer, instead of stopping."
  },
  {
    id: "locality-and-caching",
    name: "Locality & Caching",
    one_liner: "Put copies near demand; pay for speed with staleness.",
    description: "Distance is latency, and most demand is concentrated and repetitive. Keeping copies close to where they're wanted converts far, slow, expensive reads into near, fast, cheap ones. The bill arrives as staleness: every cache is a bet that the original hasn't changed since you copied it."
  },
  {
    id: "idempotency",
    name: "Idempotency",
    one_liner: "Safe retries: doing it twice equals doing it once.",
    description: "Unreliable channels force a choice: retry and risk duplicates, or don't and risk loss. Idempotent operations dissolve the dilemma. Design the action so repeating it changes nothing, and retries become free. Message ids, payment ids, and 'set' instead of 'increment' are all the same move."
  }
];

/* ---------- VOCAB_LIBRARY · the engineering vocabulary ----------
   A SEPARATE altitude from MODEL_LIBRARY. Thinking models are timeless
   reasoning patterns (mutual exclusion governs a railway block in 1861
   and a Redis lock today). These are the software profession's names for
   the same forces:

     tier "pattern"    a recurring problem→solution shape
     tier "concept"    a mechanism or property engineers reason about
     tier "technology" a concrete component you can actually deploy

   Together they form a ladder the reader can climb per layer:
     thinking model (why it's forced) → concept → technology → pattern.

   `models` links each entry back to MODEL_LIBRARY ids, which is what
   makes the ladder renderable. `software_only: true` marks entries that
   must NEVER be attached to a physical system (a gearbox has contention,
   but it does not have Kafka). Ids are a forever contract: saved
   Deconstructs reference them. */
var VOCAB_LIBRARY = [
  /* ── patterns: recurring problem shapes ── */
  { id: "realtime-updates", tier: "pattern", name: "Pushing realtime updates",
    one_liner: "Get events to users the moment they happen.",
    appears: "Chat, notifications, live dashboards, collaborative editing. Choose polling, SSE, or WebSockets, then decide where connection state lives.",
    models: ["queue-and-buffer", "feedback-loop"] },
  { id: "long-running-tasks", tier: "pattern", name: "Managing long-running tasks",
    one_liner: "Work that outlives the request gets a queue and a worker.",
    appears: "Video encoding, report generation, bulk imports. Needs job status, retries, and a dead-letter path for the ones that never succeed.",
    models: ["queue-and-buffer", "separation-of-concerns"] },
  { id: "contention", tier: "pattern", name: "Dealing with contention",
    one_liner: "Many claimants, one resource, no double-booking.",
    appears: "Seat and ticket booking, auctions, inventory, ride matching. Pick pessimistic locks, optimistic checks, or serialize through a queue.",
    models: ["mutual-exclusion"] },
  { id: "scaling-reads", tier: "pattern", name: "Scaling reads",
    one_liner: "Reads outnumber writes 100:1; serve them from copies.",
    appears: "Feeds, catalogues, profiles, anything popular. Indexes, denormalization, replicas, then caches and CDNs — each trading freshness for speed.",
    models: ["locality-and-caching", "bottleneck"] },
  { id: "scaling-writes", tier: "pattern", name: "Scaling writes",
    one_liner: "One writer node becomes the ceiling; split the work.",
    appears: "Ingestion, telemetry, messaging. Shard on a key, partition by type, buffer bursts in a queue, shed load when it still won't fit.",
    models: ["bottleneck", "separation-of-concerns"] },
  { id: "large-blobs", tier: "pattern", name: "Handling large blobs",
    one_liner: "Never push big files through your own servers.",
    appears: "Photo, video, and document upload. Presigned URLs send bytes client-to-storage directly; the app only records that it happened.",
    models: ["separation-of-concerns", "locality-and-caching"] },
  { id: "multi-step-processes", tier: "pattern", name: "Multi-step processes",
    one_liner: "A workflow that must survive a crash halfway through.",
    appears: "Checkout, order fulfilment, onboarding, payouts. Durable state per step so a restart resumes instead of restarting.",
    models: ["single-source-of-truth", "idempotency"] },
  { id: "proximity-services", tier: "pattern", name: "Proximity-based services",
    one_liner: "Find the nearby things, fast.",
    appears: "Ride hailing, delivery, store locators, matchmaking. Needs a geospatial index — a plain latitude/longitude scan does not scale.",
    models: ["locality-and-caching"] },
  { id: "saga", tier: "pattern", name: "Saga",
    one_liner: "No distributed transaction; a chain of undoable steps.",
    appears: "Booking a flight plus a hotel plus a car. Each step has a compensating action, because you cannot hold a lock across three vendors.",
    models: ["idempotency", "graceful-degradation"] },
  { id: "outbox", tier: "pattern", name: "Transactional outbox",
    one_liner: "Write the event in the same transaction as the data.",
    appears: "Anywhere a database write must reliably produce a message. Removes the 'saved but never published' gap between two systems.",
    models: ["single-source-of-truth", "idempotency"] },
  { id: "cqrs", tier: "pattern", name: "CQRS",
    one_liner: "Separate the write model from the read model.",
    appears: "When reads and writes want opposite shapes — normalized for correctness, denormalized for speed. Two models, kept in sync.",
    models: ["separation-of-concerns"] },
  { id: "event-sourcing", tier: "pattern", name: "Event sourcing",
    one_liner: "Store the events, derive the state.",
    appears: "Ledgers, audit trails, anything needing history or replay. State becomes a fold over an immutable log rather than a mutable row.",
    models: ["single-source-of-truth"] },
  { id: "load-shedding", tier: "pattern", name: "Load shedding",
    one_liner: "Refuse the least valuable work to save the rest.",
    appears: "Overload. Drop or defer low-priority requests deliberately so the system degrades on purpose instead of collapsing by accident.",
    models: ["graceful-degradation", "bottleneck"] },
  { id: "fanout", tier: "pattern", name: "Fan-out on write vs read",
    one_liner: "Pay at publish time, or pay at view time.",
    appears: "Feeds and timelines. Push into every follower's inbox (fast reads, brutal for celebrities) or assemble on request (cheap writes, slow reads).",
    models: ["locality-and-caching", "bottleneck"] },

  /* ── concepts: mechanisms and properties ── */
  { id: "cap-theorem", tier: "concept", name: "CAP theorem",
    one_liner: "Under a partition you choose consistency or availability.",
    appears: "Every replicated store. Most internet systems pick availability and accept eventual consistency; banks and bookings often do not.",
    models: ["redundancy", "graceful-degradation"] },
  { id: "sharding", tier: "concept", name: "Sharding",
    one_liner: "Split one dataset across independent servers by key.",
    appears: "When a single database cannot hold or serve the data. The shard key decides everything: bad keys create hotspots and cross-shard queries.",
    models: ["bottleneck", "separation-of-concerns"] },
  { id: "consistent-hashing", tier: "concept", name: "Consistent hashing",
    one_liner: "A ring of servers, so adding one moves almost nothing.",
    appears: "Caches, shard routing, connection assignment. Plain modulo hashing reshuffles the whole dataset the moment the server count changes.",
    models: ["locality-and-caching", "redundancy"] },
  { id: "caching", tier: "concept", name: "Caching",
    one_liner: "Keep the answer near whoever keeps asking.",
    appears: "Any expensive repeated read. Cache-aside is the default; the hard parts are invalidation, stampedes, and what happens when the cache dies.",
    models: ["locality-and-caching"] },
  { id: "indexing", tier: "concept", name: "Database indexing",
    one_liner: "Trade write cost and storage for fast lookups.",
    appears: "Every query you run twice. B-tree by default; hash for exact match, inverted for text, R-tree or geohash for space.",
    models: ["locality-and-caching", "bottleneck"] },
  { id: "data-modeling", tier: "concept", name: "Data modeling",
    one_liner: "Relational or NoSQL; normalized or denormalized.",
    appears: "The first real decision. Normalize for correctness and one source of truth; denormalize to buy read speed with duplication.",
    models: ["separation-of-concerns", "single-source-of-truth"] },
  { id: "load-balancing", tier: "concept", name: "Load balancing",
    one_liner: "Spread traffic so no single machine is the ceiling.",
    appears: "Any horizontally scaled tier. Layer 4 routes packets and is fast; layer 7 reads the request and can route by path, header, or tenant.",
    models: ["redundancy", "bottleneck"] },
  { id: "api-design", tier: "concept", name: "API design",
    one_liner: "The contract: resources, verbs, paging, limits.",
    appears: "Every client boundary. Cursor pagination beats offset at scale; rate limits and auth belong at the edge, not in each service.",
    models: ["separation-of-concerns", "trust-boundary"] },
  { id: "communication-protocols", tier: "concept", name: "Communication protocols",
    one_liner: "HTTP, WebSockets, SSE, or gRPC — pick by direction.",
    appears: "Request/response is HTTP. Server-push one way is SSE; both ways is WebSockets; internal service-to-service is often gRPC.",
    models: ["queue-and-buffer", "separation-of-concerns"] },
  { id: "idempotency-keys", tier: "concept", name: "Idempotency keys",
    one_liner: "A client-supplied id that makes a retry harmless.",
    appears: "Payments, orders, any write over an unreliable network. The server remembers the key and returns the original result instead of acting twice.",
    models: ["idempotency"] },
  { id: "consensus", tier: "concept", name: "Consensus",
    one_liner: "Getting replicas to agree on one value, despite failures.",
    appears: "Leader election, configuration, distributed locks. Raft and Paxos are the standard answers; almost nobody should implement them from scratch.",
    models: ["single-source-of-truth", "mutual-exclusion"] },
  { id: "quorum", tier: "concept", name: "Quorum reads and writes",
    one_liner: "If readers and writers overlap, you read fresh data.",
    appears: "Tunable-consistency stores. When reads plus writes exceed the replica count, every read sees the latest committed write.",
    models: ["redundancy", "single-source-of-truth"] },
  { id: "wal", tier: "concept", name: "Write-ahead log",
    one_liner: "Record the intent before changing the data.",
    appears: "Databases, filesystems, replication. Durability and crash recovery both fall out of writing the log first and applying it second.",
    models: ["single-source-of-truth", "idempotency"] },
  { id: "leader-election", tier: "concept", name: "Leader election",
    one_liner: "Exactly one node holds the right to decide.",
    appears: "Primary databases, schedulers, cron that must not run twice. The hard case is a leader that thinks it still leads after the network healed.",
    models: ["mutual-exclusion", "single-source-of-truth"] },
  { id: "backpressure", tier: "concept", name: "Backpressure",
    one_liner: "Let a slow consumer tell the producer to slow down.",
    appears: "Any pipeline. Without it, a queue absorbs the mismatch until memory or disk runs out, and the failure lands far from its cause.",
    models: ["queue-and-buffer", "feedback-loop"] },
  { id: "circuit-breaker", tier: "concept", name: "Circuit breaker",
    one_liner: "Stop calling a service that is already failing.",
    appears: "Service-to-service calls. Trips open after repeated failures, fails fast for a cooldown, then probes — stops one outage cascading.",
    models: ["graceful-degradation", "feedback-loop"] },
  { id: "bulkhead", tier: "concept", name: "Bulkhead isolation",
    one_liner: "Separate pools so one flood cannot sink the ship.",
    appears: "Shared thread pools, connections, tenants. Partition the resource so a runaway workload starves only its own compartment.",
    models: ["separation-of-concerns", "graceful-degradation"] },
  { id: "rate-limiting", tier: "concept", name: "Rate limiting",
    one_liner: "Cap how fast a caller may consume you.",
    appears: "Public APIs, abuse control, fairness between tenants. Token bucket allows bursts; leaky bucket smooths them to a constant rate.",
    models: ["queue-and-buffer", "incentive-alignment"] },
  { id: "hot-key", tier: "concept", name: "Hot key mitigation",
    one_liner: "One popular key overwhelms the shard that owns it.",
    appears: "Celebrity accounts, viral posts, flash sales. Fixes are replication of the key, request coalescing, or a local cache in front.",
    models: ["bottleneck", "locality-and-caching"] },
  { id: "optimistic-concurrency", tier: "concept", name: "Optimistic concurrency control",
    one_liner: "Assume no conflict; check a version at commit.",
    appears: "Low-contention writes. Cheap when conflicts are rare, wasteful when they are common — then you want a real lock.",
    models: ["mutual-exclusion"] },
  { id: "pessimistic-locking", tier: "concept", name: "Pessimistic locking",
    one_liner: "Take the lock first; nobody else may touch it.",
    appears: "High-contention resources like a specific seat or balance. Correct and simple, but it serializes work and can deadlock.",
    models: ["mutual-exclusion"] },
  { id: "crdt", tier: "concept", name: "CRDTs and vector clocks",
    one_liner: "Structures that merge concurrent edits without a referee.",
    appears: "Offline-first apps and collaborative editing. Causality is tracked per replica so concurrent updates converge instead of clobbering.",
    models: ["single-source-of-truth", "graceful-degradation"] },
  { id: "eventual-consistency", tier: "concept", name: "Eventual consistency",
    one_liner: "Replicas converge, given a pause in writes.",
    appears: "Most large read-heavy systems. The engineering question is not 'is it stale' but 'how stale, and who notices'.",
    models: ["graceful-degradation", "feedback-loop"] },
  { id: "tiered-storage", tier: "concept", name: "Tiered storage",
    one_liner: "Hot data on fast media, cold data on cheap media.",
    appears: "Logs, media archives, backups. Age or access frequency moves objects down the tiers automatically.",
    models: ["locality-and-caching", "separation-of-concerns"] },
  { id: "geo-distribution", tier: "concept", name: "Geographic distribution",
    one_liner: "The speed of light is a hard latency floor.",
    appears: "Global products. A cross-continent round trip costs well over 100 ms no matter how good your code is; move the data, not the packets.",
    models: ["locality-and-caching", "bottleneck"] },

  /* ── technologies: things you actually deploy (software systems only) ── */
  { id: "relational-db", tier: "technology", name: "Relational database", software_only: true,
    one_liner: "Postgres, MySQL — tables, joins, transactions.",
    appears: "The correct default. ACID transactions and constraints make whole classes of bug impossible; reach elsewhere only with a reason.",
    models: ["single-source-of-truth", "mutual-exclusion"] },
  { id: "nosql-db", tier: "technology", name: "NoSQL database", software_only: true,
    one_liner: "DynamoDB, Cassandra — flexible schema, horizontal scale.",
    appears: "Huge volume, known access patterns, no need for cross-entity transactions. You design the table around the query, not the entity.",
    models: ["separation-of-concerns", "redundancy"] },
  { id: "blob-storage", tier: "technology", name: "Blob storage", software_only: true,
    one_liner: "S3, GCS — put bytes in, get a URL back.",
    appears: "Images, video, documents, backups. Cheap, durable, and the only sane home for anything measured in megabytes.",
    models: ["separation-of-concerns"] },
  { id: "search-db", tier: "technology", name: "Search-optimized database", software_only: true,
    one_liner: "Elasticsearch — an inverted index over your text.",
    appears: "Full-text search, faceting, fuzzy matching. Kept in sync with the source of truth rather than replacing it.",
    models: ["locality-and-caching", "separation-of-concerns"] },
  { id: "api-gateway", tier: "technology", name: "API gateway", software_only: true,
    one_liner: "One front door: routing, auth, limits, logging.",
    appears: "In front of microservices, so cross-cutting concerns live in one place instead of being reimplemented per service.",
    models: ["trust-boundary", "separation-of-concerns"] },
  { id: "load-balancer", tier: "technology", name: "Load balancer", software_only: true,
    one_liner: "NGINX, ALB — spread requests across machines.",
    appears: "Any time more than one server answers the same request. Also where health checks pull dead instances out of rotation.",
    models: ["redundancy", "bottleneck"] },
  { id: "queue", tier: "technology", name: "Queue", software_only: true,
    one_liner: "SQS, RabbitMQ — buffer work, consume once.",
    appears: "Bursty or slow work that can happen later. Poor fit under about 500 ms of required latency, where the hop costs more than it saves.",
    models: ["queue-and-buffer", "separation-of-concerns"] },
  { id: "stream", tier: "technology", name: "Stream", software_only: true,
    one_liner: "Kafka, Kinesis, Flink — a retained, replayable log.",
    appears: "Many independent consumers of the same events, replay after a bug, or real-time processing. A queue forgets; a stream remembers.",
    models: ["queue-and-buffer", "single-source-of-truth"] },
  { id: "distributed-lock", tier: "technology", name: "Distributed lock", software_only: true,
    one_liner: "Redis, ZooKeeper, etcd — one holder at a time.",
    appears: "Seat holds, scheduled jobs, auctions. Always take a lease with a timeout; a lock held by a crashed process is a stuck system.",
    models: ["mutual-exclusion"] },
  { id: "distributed-cache", tier: "technology", name: "Distributed cache", software_only: true,
    one_liner: "Redis, Memcached — shared memory across your fleet.",
    appears: "Hot query results, sessions, computed aggregates, rate-limit counters. Fast, and deliberately allowed to lose data.",
    models: ["locality-and-caching"] },
  { id: "cdn", tier: "technology", name: "CDN", software_only: true,
    one_liner: "CloudFront, Cloudflare — copies near the user.",
    appears: "Static assets, media, and any cacheable response. Turns a cross-continent request into a same-city one.",
    models: ["locality-and-caching", "bottleneck"] },
  { id: "workflow-engine", tier: "technology", name: "Durable workflow engine", software_only: true,
    one_liner: "Temporal, Step Functions — code that survives crashes.",
    appears: "Multi-step business processes. The engine persists progress, so a restart resumes at the failed step rather than the beginning.",
    models: ["single-source-of-truth", "idempotency"] },
  { id: "geospatial-index", tier: "technology", name: "Geospatial index", software_only: true,
    one_liner: "PostGIS, Redis GEO, S2 — space you can query.",
    appears: "Nearest-N and radius searches. Divides the world into cells so a query touches a neighbourhood rather than every row.",
    models: ["locality-and-caching"] }
];

/* ---------- ROSETTA · the same force, in each profession's words ----------
   The 14 thinking models are universal; only the NAMES change by domain.
   Rather than build a parallel taxonomy per field (unbounded to curate, and
   it ages badly outside software), we translate the spine we already have.

   This costs the generator nothing: a layer already names its thinking model,
   and meta.domain names the system's field, so "called here" and "called
   elsewhere" are both derivable with no extra generated field.

   Entries are deliberately SPARSE. A model with no honest term in a domain is
   omitted rather than given an invented one. */
var DOMAINS = [
  { id: "software",   label: "Software" },
  { id: "marketing",  label: "Marketing" },
  { id: "operations", label: "Operations" },
  { id: "biology",    label: "Living systems" },
  { id: "economics",  label: "Markets & money" },
  { id: "mechanical", label: "Machines" },
  { id: "social",     label: "Institutions" }
];

var ROSETTA = {
  "first-principles": {
    software: "clean-room rewrite", marketing: "incrementality / holdout test",
    operations: "zero-based design", biology: "knockout experiment",
    economics: "counterfactual / opportunity cost", mechanical: "clean-sheet design",
    social: "constitutional design"
  },
  "inversion": {
    software: "making invalid states unrepresentable", marketing: "pre-mortem",
    operations: "FMEA / poka-yoke", biology: "negative selection",
    economics: "stress testing", mechanical: "fail-safe interlock",
    social: "checks and balances"
  },
  "bottleneck": {
    software: "hot partition / critical path", marketing: "funnel drop-off",
    operations: "the constraint (Theory of Constraints)", biology: "rate-limiting step",
    economics: "the scarce factor", mechanical: "choke point",
    social: "approval chokepoint"
  },
  "feedback-loop": {
    software: "telemetry / control loop", marketing: "multi-touch attribution",
    operations: "statistical process control", biology: "homeostasis",
    economics: "the price signal", mechanical: "governor / closed-loop control",
    social: "accountability loop"
  },
  "single-source-of-truth": {
    software: "system of record", marketing: "single customer view",
    operations: "the master schedule", biology: "the germline genome",
    economics: "the ledger", mechanical: "the datum reference",
    social: "the official register"
  },
  "mutual-exclusion": {
    software: "mutex / lock / lease", marketing: "exclusivity / roadblock buy",
    operations: "machine allocation", biology: "competitive inhibition",
    economics: "exclusive rights", mechanical: "interlock / block token",
    social: "right of way"
  },
  "queue-and-buffer": {
    software: "message queue / backpressure", marketing: "nurture sequence",
    operations: "WIP buffer / safety stock", biology: "glycogen reserve",
    economics: "inventory / float", mechanical: "accumulator / surge tank",
    social: "the waiting list"
  },
  "redundancy": {
    software: "replication / failover", marketing: "channel diversification",
    operations: "dual sourcing", biology: "paired organs / gene duplication",
    economics: "diversification / hedging", mechanical: "backup system",
    social: "succession planning"
  },
  "separation-of-concerns": {
    software: "modularity / microservices", marketing: "segmentation",
    operations: "cellular manufacturing", biology: "cell compartments",
    economics: "division of labour", mechanical: "modular subsystems",
    social: "separation of powers"
  },
  "trust-boundary": {
    software: "zero trust / end-to-end encryption", marketing: "consent & first-party data",
    operations: "incoming quality gate", biology: "the cell membrane",
    economics: "escrow / counterparty risk", mechanical: "containment",
    social: "jurisdiction / chain of custody"
  },
  "incentive-alignment": {
    software: "quota and pricing design", marketing: "commission & affiliate design",
    operations: "piece rates", biology: "symbiosis / mutualism",
    economics: "mechanism design / principal-agent", social: "law and enforcement"
  },
  "graceful-degradation": {
    software: "circuit breaker / load shedding", marketing: "always-on fallback",
    operations: "reduced-rate running", biology: "dormancy / triage",
    economics: "the trading halt", mechanical: "limp-home mode",
    social: "continuity of government"
  },
  "locality-and-caching": {
    software: "cache / CDN / replica", marketing: "geo-targeting",
    operations: "forward stocking", biology: "local energy stores",
    economics: "warehousing", mechanical: "reservoir near the load",
    social: "the local branch"
  },
  "idempotency": {
    software: "idempotency key", marketing: "conversion dedup / suppression list",
    operations: "duplicate-order guard", biology: "the refractory period",
    economics: "double-entry reconciliation", mechanical: "ratchet / detent",
    social: "one person, one vote"
  }
};

/* id lookups — the vocabulary and models are referenced by id from saved
   documents, so every consumer resolves through these */
function domainLabel(id) { for (const d of DOMAINS) if (d.id === id) return d.label; return null; }
/* every domain name for a model: [{domain,label,term}], the doc's own domain first */
function rosettaFor(modelId, here) {
  const map = ROSETTA[modelId];
  if (!map) return [];
  const out = [];
  DOMAINS.forEach(d => { if (map[d.id]) out.push({ domain: d.id, label: d.label, term: map[d.id], here: d.id === here }); });
  out.sort((a, b) => (b.here ? 1 : 0) - (a.here ? 1 : 0));
  return out;
}

function vocabById(id) { for (const v of VOCAB_LIBRARY) if (v.id === id) return v; return null; }
function modelById(id) { for (const m of MODEL_LIBRARY) if (m.id === id) return m; return null; }

/* ---------- NUMBERS · latency, throughput, capacity ----------
   Surfaced in the Under load band, where the reader is already asking the
   scaling question. Orders of magnitude, not benchmarks: the point is to
   make an estimate defensible, not exact. */
var NUMBERS_LIBRARY = [
  { group: "Latency", rows: [
    ["Memory read", "~100 ns"],
    ["SSD random read", "~100 µs"],
    ["Round trip, same datacenter", "~0.5 ms"],
    ["Round trip, cross-country", "~40 ms"],
    ["Round trip, cross-continent", "~150 ms"]
  ]},
  { group: "Throughput (single node)", rows: [
    ["Relational database, simple queries", "~10–20k / sec"],
    ["Redis / in-memory cache", "~100k+ ops / sec"],
    ["Kafka partition", "~100k msgs / sec"],
    ["Web server, open connections", "~100k with tuning"]
  ]},
  { group: "Size", rows: [
    ["1M rows × 1 KB", "1 GB"],
    ["Typical photo", "~1–5 MB"],
    ["1080p video", "~5 Mbps · ~2.5 GB / hour"],
    ["A day of logs, mid-size service", "~10–100 GB"]
  ]}
];

/* ---------- UI COPY ---------- */
var COPY = {
  libraryTitle: "Library",
  sampleHeading: "Sample Deconstructs",
  sampleNote: "Worked examples that set the bar for a Deconstruct — and the path in Track walks them in order.",
  yoursHeading: "Your Deconstructs",
  yoursEmpty: "Nothing here yet. Name any system above and Vitruvian will take it apart, failure by failure.",
  deconstructPlaceholder: "Name a system to deconstruct…",
  deconstructBtn: "Deconstruct",
  ownDesignLink: "Building something? Dissect your design →",
  ownDesignKicker: "Dissection",
  ownDesignTitle: "Dissect your design",
  ownDesignLede: "Describe the system you're building: the pieces, what it must never get wrong, where you expect load. Vitruvian rebuilds it failure by failure and shows what breaks first.",
  ownDesignPlaceholder: "e.g. A booking app where vendors set their availability and customers reserve time slots. Two customers must never book the same slot; vendors get notified the instant a booking lands; I expect big spikes when a popular vendor opens their calendar…",
  ownDesignBtn: "Dissect my design",
  audienceModes: [
    { id: "beginner",   label: "Beginner" },
    { id: "enthusiast", label: "Enthusiast" },
    { id: "developer",  label: "Developer" }
  ],
  gateKicker: "Your turn before the reveal",
  gateHint1: "Show the thinking model",
  gateHint2: "One more hint",
  gateReveal: "Reveal the solution",
  gateCompare: "Check my answer (AI)",
  askTitle: "Probe this layer",
  askPlaceholder: "One question, e.g. \"why not just use timestamps?\"",
  askBtn: "Probe",
  whatifMenu: "Graft… (propose a change)",
  whatifKicker: "Graft",
  whatifLede: "Propose a change to this system. Vitruvian shows what it does to the architecture, which invariants it strengthens or threatens, and whether the body accepts the graft, judged by the system's own rules.",
  whatifPlaceholder: "e.g. add an HTML renderer to the terminal · cache reads at the edge · drop the acknowledgement step",
  whatifBtn: "Run the graft",
  whatifThinking: "Weighing it against the invariants…",
  whatifVerdicts: { improves: "The graft takes: the system improves", mixed: "It takes, with scars: a real tradeoff", harmful: "Rejected: works against the system" },
  gateCompareOffline: "AI comparison needs a connection and an API key (Settings). Your answer is saved, so you can compare it against the reveal yourself.",
  keyNotice: "Your key is stored on this device only and sent only to Anthropic.",
  costNote: "A Deconstruct typically costs a few cents to a few tens of cents of API usage, depending on the model.",
  modelCostNote: "Rough cost per Deconstruct: haiku-4-5 ≈ $0.10 · sonnet-5 ≈ $0.30 · opus-4-8 ≈ $0.55 · fable-5 ≈ $1.20. Fable is the most capable and falls back to Opus if it declines a request.",
  pricingUrl: "https://www.anthropic.com/pricing",
  privacyNote: "Everything lives on this device. Deconstructs, attempts, and your key are never sent anywhere except your own calls to Anthropic.",
  offlineGenNote: "Generation needs a connection. Reading never does.",
  bridgeToast: "Reference notes copied. Paste into UX-First Studio's Structure It station.",
  shareMenu: "Share link",
  shareCopied: "Link copied. Anyone can open this Deconstruct",
  shareLocalNote: "This Deconstruct lives on this device. Export the .json to share it.",
  exportPngMenu: "Export diagram (.png)",
  requestLink: "Request a system →",
  studioUrl: "https://bate-epey93.github.io/uxfirst-studio/",
  /* ---------- LANDING (first-run explainer) ---------- */
  landing: {
    kicker: "Welcome to Vitruvian",
    headline: "Take anything apart.\nPut it back together. Now you get it.",
    lede: "Everyday systems, deconstructed one failure at a time.",
    sections: [
      { icon: "whatItIs", title: "What it is",
        body: "Pick a system. Vitruvian strips it to its bones, then rebuilds it layer by layer, each layer forced by a real failure. A diagram grows as it comes together." },
      { icon: "whoFor", title: "Who it's for",
        body: "Curious minds, systems-design enthusiasts, and developers prepping for architecture interviews. Three reading levels, from plain English to engineer." },
      { icon: "whyWorks", title: "Why it works",
        body: "You remember what you rebuild. Design each fix yourself before the reveal, and collect the thinking models that repeat across systems." },
      { icon: "howTo", title: "How to use it",
        body: "Start with a sample Deconstruct. Add your Anthropic API key in Settings to deconstruct anything you name, or submit your own design and see where it breaks first. Works offline; installs to your home screen." }
    ],
    cta: "Start deconstructing →",
    footnote: "No account. No cloud. Your Deconstructs stay on this device."
  },

  /* ---------- TUTORIAL — 'How to read a Deconstruct' (visitable anytime) ---------- */
  tutorial: {
    kicker: "How to read a Deconstruct",
    headline: "Every Deconstruct is the same shape.",
    lede: "A Vitruvian Deconstruct rebuilds a system from nothing, one failure at a time. Here's how to read the pieces, and, for developers, how to lift a technical spec out of one.",
    reading: {
      title: "The path through a Deconstruct",
      steps: [
        ["Essence", "The system in one breath, plus a few surprising, checkable facts."],
        ["The Skeleton", "The irreducible core: who wants what, the invariants (what must never be false), the pieces, the flows, and the hard constraints physics and economics impose."],
        ["The rebuild", "4–7 layers, the heart of it. Each layer is forced by a concrete failure of the version before it, often a real, dated disaster. You watch the design become necessary, not just described."],
        ["Stress tests", "Push the finished system somewhere nasty and see how it copes, or where it honestly breaks."],
        ["Transfer", "The system-neutral principles, and where the same shapes recur in other systems."]
      ]
    },
    cards: {
      title: "Inside each layer: the cards",
      note: "One layer, read top to bottom. Several cards are interactive; tap to locate them on the diagram.",
      items: [
        ["problem", "The problem", "The failure that forces this layer to exist. Tap to flash what breaks on the diagram, in red."],
        ["model", "Thinking model", "The named, reusable pattern that cracks the problem (there are 14). Tap any model in the Models index to see it recur across systems."],
        ["solution", "What was actually built", "The mechanism itself. Tap to light what this layer adds to the diagram, in teal."],
        ["lens", "For the people · Under the hood", "Two lenses side by side: what users gain and what they pay, versus how it works and the transferable principle."],
        ["tradeoff", "The tradeoff", "What this layer sacrifices. Safety costs capacity; caching costs freshness."],
        ["scale", "Under load", "How the mechanism holds as load grows: its scaling property, its ceiling, or the sharding it forces. Tap to trace the load path in gold."],
        ["defends", "Defends", "Which invariants from the strip-down this layer protects, by number. Tap a chip to light the mechanism on the diagram that defends it."],
        ["dev", "For engineers", "Opens with 'Start here' — a concrete coding approach (the data structure, algorithm, or pattern) to begin solving the layer's problem. Then maps each mechanism to its software concept, plus interview probes. In Developer mode this reads as spec material."],
        ["analogy", "In everyday terms", "One plain analogy, for when an idea needs grounding."]
      ]
    },
    diagram: {
      title: "Reading the diagram",
      intro: "The diagram grows as the system does; every layer adds to it and nothing re-arranges. Colour means role, shape means kind, arrows show what moves.",
      nodeKinds: [
        ["actor", "Actor", "a person or party"],
        ["store", "Store", "where things wait or accumulate"],
        ["process", "Process", "where work happens"],
        ["channel", "Channel", "what things move through"]
      ],
      edgeKinds: [
        ["payload", "Payload", "the thing the system exists to move (solid line). This is the load path."],
        ["control", "Control", "signals and permissions (dashed), often flowing back against the payload."],
        ["money", "Money", "value changing hands (gold, dotted)."]
      ],
      extra: [
        ["Lanes & colour", "Horizontal bands are semantic roles (People, Service, Control, Money), each with its own colour. An arrow wears the colour of the lane it comes from, so you can see who drives what."],
        ["The red pulse", "At a gate, or when you tap the problem card, the parts about to break pulse red. You see the failure before the fix."],
        ["Spotlight", "Tap a card to light its parts and dim the rest: the problem card lights what breaks (red), the solution card lights what's added (teal), and Under load traces the path load travels (gold)."],
        ["Trace a part", "Tap any node to light it and every edge touching it; the rest dims, so you can follow one part's whole reach. Tap it again to clear."],
        ["Zoom in ⊕", "Some nodes are whole systems in their own right and carry a ⊕ badge. Tap it to open that sub-system as its own Deconstruct, and follow the breadcrumb back up. Systems nest as deep as the library goes."],
        ["Pan & scrub", "Dense diagrams pan sideways. Drag the scrubber (0…N) under the diagram to sweep it from the naive baseline to the finished system."]
      ]
    },
    controls: {
      title: "Controls",
      items: [
        ["Audience: B / E / D", "Three registers of the same Deconstruct: Beginner (plain language, everyday analogies), Enthusiast (the default), and Developer (adds the engineer mappings and interview probes). Switch anytime; your place is kept."],
        ["Step & scrub", "Move layer by layer with Prev / Next, or drag the scrubber to sweep the diagram across every state."],
        ["Challenge mode", "Off by default. Turn it on from the ⋯ menu to hide each solution behind a design-it-first gate: you predict the fix, then compare."]
      ]
    },
    explore: {
      title: "Go deeper: simulate & interrogate",
      note: "Buttons under the diagram, plus more in the ⋯ menu. This is where a Deconstruct stops being a picture and starts behaving like the system.",
      items: [
        ["Pulse ▶ / ⟲ replay", "Send live traffic through the current state. Payloads travel the flow path, crash red into whatever's broken, and (under ◉ load) congest where the system saturates. ⟲ replay re-enacts the exact historical failure, arrival by arrival."],
        ["Fault injection", "While a pulse is running, tap any node to kill it. Traffic piles up behind the dead node and everything downstream starves — chaos engineering as a toy. Tap it again to revive it."],
        ["Live HUD", "While traffic flows, a small readout shows throughput (delivered/min), how many payloads are in flight, and crashes. Under load, watch delivered plateau while in-flight climbs: saturation you can count, not just see."],
        ["Race spotlight ⇉", "Rings every node with two or more concurrent writers — the places two flows can arrive at once and race. The count tells you how many contention points the design carries."],
        ["Sequence view", "In the ⋯ menu: the same state as an interaction timeline — who sends what to whom, top to bottom, in the order it happens. The diagram shows structure; this shows behaviour."],
        ["Probe a layer", "Ask one bounded question of any layer; the answer is grounded in that layer's own mechanism. Needs your Anthropic API key (Settings)."],
        ["Graft a change", "In the ⋯ menu: propose a change and see it ghosted onto the architecture — dashed blueprint ink — with an honest verdict (improves · mixed · harmful) argued from the system's own invariants. Pulse runs through the graft too."],
        ["Known as… (the engineering vocabulary)", "In Developer mode, each layer names what the profession calls what it does: patterns (problem shapes), concepts (mechanisms), technologies (things you deploy). Tap a chip to climb the ladder — from the timeless thinking model that forces the layer, down to the component you'd actually deploy — and to see where the same force recurs across your other Deconstructs. Browse them all from Models → The engineering vocabulary."],
        ["Also called…", "Every thinking model has a different name in every field. A layer's model card shows what this system's own profession calls it — and, folded underneath, what marketers, engineers, biologists, economists and institutions call the same force. Frequency capping is rate limiting; attribution is telemetry. That recurrence is the whole point of taking systems apart."],
        ["Not yet addressed", "When you Dissect your own design, the overview names the concerns your description hasn't answered yet — contention, scaling reads, idempotency — each with a sentence on why it will bite and roughly when. A to-do list, not a scolding."]
      ]
    },
    forDev: {
      title: "For developers: reading a Deconstruct as a spec",
      intro: "A Deconstruct is already shaped like a design document. Switch to Developer mode first (it surfaces the mappings and probes the other registers tuck away), then lift it across:",
      map: [
        ["The Skeleton", "system context: actors, invariants (your correctness guarantees), entities, data flows, and hard constraints."],
        ["Each layer's mechanism + principle", "an architecture decision record: what you built and the rule it encodes."],
        ["Under load", "the scaling / capacity section: throughput ceilings, bottlenecks, and the sharding or caching strategy."],
        ["Tradeoffs + stress tests", "your risk register and failure-mode analysis."],
        ["For-engineers mappings", "the concrete tech: the software concept each mechanism maps to."],
        ["Transfer principles", "the reusable patterns to carry into your own design."]
      ]
    },
    cta: "Got it. Back to deconstructing"
  },

  genPhases: {
    start:      "Reading the system…",
    strip_down: "Finding the skeleton…",
    visual:     "Drawing the baseline…",
    layers:     "Rebuilding, layer by layer…",
    stress:     "Stress-testing…",
    transfer:   "Extracting principles…"
  }
};
